# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fee1f0b29437f4356e90f8100b1e7dc8fab66c3fb4dd8533812dba01ef2841ab61708fa9708e001fb808f076a1a4a0df87ef32ca66a5c5f38a9003f54141116c

test:
  secret_key_base: 44b2308a6fede9143a3da24d6017824adf7c3f54f3d3e3a98eddb258944e7be9047a3e16f14391c1e0c8a36120452f739cbf37cf83d254d2d6f66a65927e1835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
